services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017

  app:
    image: ricardodcpina/real-estate-rental
    ports:
      - 3000:3000
    depends_on:
      - mongo